CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  uid VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  is_approved BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price_piece NUMERIC(10,2) DEFAULT 0,
  price_kg NUMERIC(10,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  uid VARCHAR(255) NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
  products JSONB NOT NULL,
  status VARCHAR(50) DEFAULT 'pending'
);
