CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  uid VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  display_name VARCHAR(255),
  auth_type VARCHAR(20) DEFAULT 'google',
  is_admin BOOLEAN DEFAULT FALSE,
  is_approved BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price_piece NUMERIC(10,2) DEFAULT 0,
  price_kg NUMERIC(10,2) DEFAULT 0,
  image VARCHAR(255),
  category VARCHAR(100) DEFAULT 'general',
  sell_by VARCHAR(20) DEFAULT 'both',
  available BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  uid VARCHAR(255) NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
  products JSONB NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  is_delivered BOOLEAN DEFAULT FALSE,
  delivered_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_uid ON orders(uid);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE TABLE IF NOT EXISTS order_favorites (
  id SERIAL PRIMARY KEY,
  uid VARCHAR(255) NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  products JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_requests (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  uid VARCHAR(255) NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
  request_type VARCHAR(50) NOT NULL,
  message TEXT,
  admin_response TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  proposed_changes JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invitations (
  id SERIAL PRIMARY KEY,
  code VARCHAR(64) UNIQUE NOT NULL,
  created_by VARCHAR(255) NOT NULL,
  used_by VARCHAR(255),
  used_at TIMESTAMP,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
