-- Insert categories
INSERT INTO categories (name) VALUES
  ('frutas'),
  ('verduras'),
  ('legumbres'),
  ('hierbas'),
  ('hongos'),
  ('frutos_secos'),
  ('general')
ON CONFLICT (name) DO NOTHING;

-- Upsert products
INSERT INTO products (id, name, price_piece, price_kg, image, category, sell_by) VALUES
  (1,  'Avena',                       0, 35.00, '/assets/product-1.webp', 'general',       'kg'),
  (2,  'Aguacate',                 15.00, 45.00, '/assets/product-2.webp', 'frutas', 'both'),
  (3,  'Ajo',                       5.00, 80.00, '/assets/product-3.webp', 'verduras',      'both'),
  (4,  'Apio',                     15.00,  0, '/assets/product-4.webp', 'verduras',      'pieces'),
  (5,  'Apio (bolsa)',             20.00,  0, NULL, 'verduras',      'pieces'),
  (6,  'Arugula baby (caja)',      35.00,  0, '/assets/product-6.webp', 'verduras',      'pieces'),
  (7,  'Arugula baby (manojo)',    20.00,  0, NULL, 'verduras',      'pieces'),
  (8,  'Betabel (manojo)',         15.00,  0, '/assets/product-8.webp', 'verduras',      'pieces'),
  (9,  'Berros (manojo)',          12.00,  0, '/assets/product-9.webp', 'hierbas',       'pieces'),
  (10, 'Betabel',                  10.00, 22.00, NULL, 'verduras',      'both'),
  (11, 'Blueberry (bote 1lt)',     65.00,  0, '/assets/product-11.webp', 'frutas',        'pieces'),
  (12, 'Blueberry (caja)',         45.00,  0, NULL, 'frutas',        'pieces'),
  (13, 'Brocoli (bolsa)',          25.00,  0, '/assets/product-13.webp', 'verduras', 'pieces'),
  (14, 'Calabaza',                  8.00, 18.00, '/assets/product-14.webp', 'verduras', 'both'),
  (15, 'Camote rojo',              10.00, 22.00, '/assets/product-15.webp', 'verduras',      'both'),
  (16, 'Cebolla',                   6.00, 16.00, '/assets/product-16.webp', 'verduras', 'both'),
  (17, 'Cebolla cambray (manojo)', 10.00,  0, '/assets/product-17.webp', 'verduras',      'pieces'),
  (18, 'Cebolla morada',            8.00, 20.00, '/assets/product-18.webp', 'verduras',      'both'),
  (19, 'Cebolla rabo',              8.00,  0, '/assets/product-19.webp', 'verduras',      'pieces'),
  (20, 'Cebolla rabo (manojo)',    10.00,  0, NULL, 'verduras',      'pieces'),
  (21, 'Cebollin (manojo)',        12.00,  0, '/assets/product-21.webp', 'hierbas',       'pieces'),
  (22, 'Champinones a granel',      0, 90.00, '/assets/product-22.webp', 'hongos',        'kg'),
  (23, 'Champipack (caja)',        30.00,  0, NULL, 'hongos',        'pieces'),
  (24, 'Chayote',                   5.00, 14.00, '/assets/product-24.webp', 'verduras', 'both'),
  (26, 'Chile mirasol',            5.00, 120.00, '/assets/product-26.webp', 'verduras',     'both'),
  (27, 'Chile de arbol',           3.00, 150.00, '/assets/product-27.webp', 'verduras',     'both'),
  (28, 'Chile jalapeno',            3.00, 30.00, '/assets/product-28.webp', 'verduras',      'both'),
  (29, 'Chile verde',               3.00, 28.00, '/assets/product-29.webp', 'verduras',      'both'),
  (30, 'Cilantro (manojo)',         8.00,  0, '/assets/product-30.webp', 'hierbas',       'pieces'),
  (31, 'Col',                      15.00,  0, '/assets/product-31.webp', 'verduras',      'pieces'),
  (32, 'Coliflor',                 20.00,  0, '/assets/product-32.webp', 'verduras',      'pieces'),
  (33, 'Curcuma',                  10.00, 120.00, '/assets/product-33.webp', 'verduras',      'both'),
  (34, 'Ejotes',                     0, 35.00, '/assets/product-34.webp', 'verduras',      'kg'),
  (35, 'Elotes',                   10.00,  0, '/assets/product-35.webp', 'verduras',      'pieces'),
  (36, 'Esparragos (manojo)',      35.00,  0, '/assets/product-36.webp', 'verduras',      'pieces'),
  (37, 'Espinaca popeye (bolsa)',  20.00,  0, '/assets/product-37.webp', 'verduras',      'pieces'),
  (38, 'Espinacas baby (caja)',    35.00,  0, NULL, 'verduras',      'pieces'),
  (39, 'Espinacas (manojo)',       15.00,  0, NULL, 'verduras',      'pieces'),
  (40, 'Frambuesa (bote 1lt)',     70.00,  0, '/assets/product-40.webp', 'frutas',        'pieces'),
  (41, 'Frambuesa (caja)',          50.00,  0, NULL, 'frutas',        'pieces'),
  (42, 'Fresas (caja)',            35.00,  0, '/assets/product-42.webp', 'frutas', 'pieces'),
  (43, 'Guayaba',                  10.00, 22.00, '/assets/product-43.webp', 'frutas', 'both'),
  (44, 'Garbanzo',                   0, 45.00, '/assets/product-44.webp', 'legumbres',     'kg'),
  (45, 'Granada',                  15.00, 40.00, '/assets/product-45.webp', 'frutas',        'both'),
  (46, 'Hierbabuena (manojo)',     10.00,  0, '/assets/product-46.webp', 'hierbas',       'pieces'),
  (47, 'Jengibre',                 15.00, 90.00, '/assets/product-47.webp', 'verduras',      'both'),
  (48, 'Jicama',                   12.00, 20.00, '/assets/product-48.webp', 'verduras',      'both'),
  (49, 'Jitomate',                 10.00, 24.00, '/assets/product-49.webp', 'verduras', 'both'),
  (50, 'Kiwi',                     10.00, 60.00, '/assets/product-50.webp', 'frutas',        'both'),
  (51, 'Lechuga (bolsa)',          20.00,  0, '/assets/product-51.webp', 'verduras',      'pieces'),
  (52, 'Lechuga romana',           15.00,  0, '/assets/product-52.webp', 'verduras',      'pieces'),
  (53, 'Lentejas',                   0, 38.00, '/assets/product-53.webp', 'legumbres',     'kg'),
  (54, 'Limon con semilla',          0, 20.00, '/assets/product-54.webp', 'frutas', 'kg'),
  (55, 'Limon sin semilla',          0, 25.00, NULL, 'frutas', 'kg'),
  (56, 'Mandarina',               5.00, 25.00, '/assets/product-56.webp', 'frutas',        'both'),
  (57, 'Manzana roja',            12.00, 32.00, '/assets/product-57.webp', 'frutas', 'both'),
  (58, 'Manzana verde',           12.00, 32.00, '/assets/product-58.webp', 'frutas', 'both'),
  (59, 'Manzana golden',          12.00, 30.00, '/assets/product-59.webp', 'frutas',        'both'),
  (60, 'Melon chino',             25.00,  0, '/assets/product-60.webp', 'frutas',        'pieces'),
  (61, 'Melon valenciano',         30.00,  0, '/assets/product-61.webp', 'frutas',        'pieces'),
  (62, 'Naranja con semilla',       5.00, 18.00, '/assets/product-62.webp', 'frutas',        'both'),
  (63, 'Naranja sin semilla',       6.00, 22.00, NULL, 'frutas',        'both'),
  (64, 'Nopales',                   8.00, 20.00, '/assets/product-64.webp', 'verduras',      'both'),
  (65, 'Nuez',                       0, 180.00, '/assets/product-65.webp', 'frutos_secos',  'kg'),
  (66, 'Oregano seco',               0, 200.00, '/assets/product-66.webp', 'hierbas',       'kg'),
  (67, 'Papa',                      8.00, 18.00, '/assets/product-67.webp', 'verduras', 'both'),
  (68, 'Papa cambray',               0, 25.00, '/assets/product-68.webp', 'verduras',      'kg'),
  (69, 'Papaya',                   25.00,  0, '/assets/product-69.webp', 'frutas', 'pieces'),
  (70, 'Pepino',                    6.00, 18.00, '/assets/product-70.webp', 'verduras',      'both'),
  (71, 'Pera',                     12.00, 45.00, '/assets/product-71.webp', 'frutas',        'both'),
  (72, 'Perejil (manojo)',          8.00,  0, '/assets/product-72.webp', 'hierbas',       'pieces'),
  (73, 'Poro',                     15.00,  0, '/assets/product-73.webp', 'verduras',      'pieces'),
  (74, 'Piña',                     25.00,  0, '/assets/product-74.webp', 'frutas', 'pieces'),
  (75, 'Platano',                    0, 18.00, '/assets/product-75.webp', 'frutas', 'kg'),
  (76, 'Penca de platano',         20.00,  0, '/assets/product-76.webp', 'frutas',        'pieces'),
  (77, 'Penca de platano dominico',18.00,  0, '/assets/product-77.webp', 'frutas', 'pieces'),
  (78, 'Platano macho',            10.00,  0, '/assets/product-78.webp', 'frutas',        'pieces'),
  (79, 'Penca de platano macho',   25.00,  0, '/assets/product-79.webp', 'frutas',        'pieces'),
  (80, 'Rabanos (manojo)',         10.00,  0, '/assets/product-80.webp', 'verduras',      'pieces'),
  (81, 'Sandia bola',              35.00,  0, '/assets/product-81.webp', 'frutas',        'pieces'),
  (82, 'Sandia grande',            50.00,  0, NULL, 'frutas',        'pieces'),
  (83, 'Tamarindo',                  0, 40.00, '/assets/product-83.webp', 'frutas',        'kg'),
  (84, 'Tejocote',                   0, 30.00, '/assets/product-84.webp', 'frutas',        'kg'),
  (85, 'Tomate',                    8.00, 20.00, NULL, 'verduras', 'both'),
  (86, 'Tomate cherry',              0, 60.00, '/assets/product-86.webp', 'verduras',      'kg'),
  (87, 'Tomate cherry (caja)',     35.00,  0, NULL, 'verduras',      'pieces'),
  (88, 'Tomatillo',                  0, 20.00, '/assets/product-88.webp', 'verduras',      'kg'),
  (89, 'Toronja',                    0, 25.00, '/assets/product-89.webp', 'frutas',        'kg'),
  (90, 'Uvas moradas',               0, 55.00, '/assets/product-90.webp', 'frutas',        'kg'),
  (91, 'Uvas moradas (bolsa)',     40.00,  0, NULL, 'frutas',        'pieces'),
  (92, 'Uvas verdes',                0, 55.00, '/assets/product-92.webp', 'frutas', 'kg'),
  (93, 'Uvas verdes (bolsa)',      40.00,  0, NULL, 'frutas',        'pieces'),
  (94, 'Verdolagas (manojo)',      10.00,  0, '/assets/product-94.webp', 'hierbas',       'pieces'),
  (95, 'Yuca',                     15.00,  0, '/assets/product-95.webp', 'verduras',      'pieces'),
  (96, 'Zanahoria',                 5.00, 14.00, '/assets/product-96.webp', 'verduras', 'both'),
  (97, 'Baby zanahoria (bolsa)',   25.00,  0, '/assets/product-97.webp', 'verduras',      'pieces'),
  (98, 'Zarzamora (bote 1lt)',     65.00,  0, '/assets/product-98.webp', 'frutas',        'pieces'),
  (99, 'Zarzamora (caja)',         45.00,  0, NULL, 'frutas',        'pieces'),
  (100, 'Tuna',                    8.00, 25.00, '/assets/product-100.webp', 'frutas',        'both'),
  (101, 'Durazno',                12.00, 40.00, '/assets/product-101.webp', 'frutas',        'both'),
  (102, 'Pimiento rojo',          12.00, 65.00, '/assets/product-102.webp', 'verduras',      'both'),
  (103, 'Pimiento verde',         10.00, 55.00, '/assets/product-103.webp', 'verduras',      'both'),
  (104, 'Pimiento naranja',       12.00, 65.00, '/assets/product-104.webp', 'verduras',      'both'),
  (105, 'Pimiento amarillo',      12.00, 65.00, '/assets/product-105.webp', 'verduras',      'both')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  price_piece = EXCLUDED.price_piece,
  price_kg = EXCLUDED.price_kg,
  image = COALESCE(EXCLUDED.image, products.image),
  category = EXCLUDED.category,
  sell_by = EXCLUDED.sell_by;

-- Reset sequence to be after the last seeded id
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));

-- Remove old products that are no longer in the catalog
DELETE FROM products WHERE id > 105;
DELETE FROM products WHERE id = 25;
